export module ChatConstants {
	export let ActionTypes = {
		CLICK_THREAD: 'CREATE_THREAD',
		CREATE_MESSAGE: 'CREATE_MESSAGE',
		RECEIVE_RAW_CREATED_MESSAGE: 'RECEIVE_RAW_CREATED_MESSAGE',
		RECEIVE_MESSAGE: 'RECEIVE_MESSAGE',
		RECEIVE_MESSAGES: 'RECEIVE_MESSAGES'
	}
}

